line_length:
- 250 # warning
- 300 # error
disabled_rules:
- trailing_whitespace
- unused_optional_binding
- superfluous_disable_command
- computed_accessors_order
- vertical_whitespace
- file_length
- identifier_name
- type_body_length
- nesting
- syntactic_sugar
- weak_delegate
- for_where
- cyclomatic_complexity
- unused_setter_value
- empty_enum_arguments
- function_body_length
- operator_whitespace
- redundant_optional_initialization
- type_name
- control_statement
